#!/bin/bash -v

#
# Point to the actual application executable
#
realpath=`readlink -f "$0"`
directory=`dirname "$realpath"`

OS_type=`cat /etc/os-release | grep ID_LIKE | cut -d= -f2`
OS=`cat /etc/os-release | grep ID | cut -d= -f2`

if [ "$OS_type" == "debian" ]
then
	echo "using debian"
elif [ "$OS_type" == "rhel fedora" ] && [ "$OS" != "centos" ]
then
	if [ -z "$LD_LIBRARY_PATH" ]; then
		export LD_LIBRARY_PATH="$directory/../libs_rh_linux64"
	else
		export LD_LIBRARY_PATH="$directory/../libs_rh_linux64:$LD_LIBRARY_PATH"
	fi

	export QT_QPA_PLATFORM_PLUGIN_PATH="$directory/../plugins_rh_linux64"
fi

"$directory"/../exe_rh_linux64/wb_view
#exit $?
