#!/bin/csh -f
#$Header: /data/petsun4/data1/solaris/csh_scripts/RCS/brec,v 1.1 2018/08/19 02:50:42 avi Exp $
#$Log: brec,v $
# Revision 1.1  2018/08/19  02:50:42  avi
# Initial revision
#

if ($#argv < 1) then
	echo "Usage:	brec <my_file[.rec]> [-depth_limit]"
	exit
endif

set file = $1
if ($file:e != "rec") set file = $file.rec

if (! -e $file) then
	echo $file not found
	exit -1
endif

@ dlimit = 0
if (${#argv} == 2) then
	set dlimit = `echo $argv[2] | awk '{print substr($0,2)}'`
endif

set dir = `which brec | tail -1`; set dir = $dir:h
if (`uname -s` == "SunOS") then
	set PROG = nawk
else
	set PROG = gawk
endif
${PROG} -f $dir/brec.awk dlimit=$dlimit $file

exit 0
