function plot_movement_parameters(ChartName,YMatrix1,OutputFilename)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Sep-2016 11:29:41

% Create figure
figure1 = figure('Position',[0,0,1440,720]);

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'Position',[0.0245947456679709 0.0323232323232323 0.969256567915036 0.931313131313131]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 length(YMatrix1(:,1))]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','lin x','Color',[0 0 0]);
set(plot1(2),'Color',[1 0 0],'DisplayName','lin y');
set(plot1(3),'Color',[0 0 1],'DisplayName','lin z');
set(plot1(4),'LineWidth',2,'LineStyle','--','DisplayName','rot x',...
    'Color',[0 0 0]);
set(plot1(5),'LineWidth',2,'LineStyle','--','Color',[1 0 0],...
    'DisplayName','rot y');
set(plot1(6),'LineWidth',2,'LineStyle','--','Color',[0 0 1],...
    'DisplayName','rot z');

% Create xlabel
xlabel('Time');

% Create ylabel
ylabel('mm of change');

% Create title
title({ChartName});

% Create legend
legend(axes1,'show');

set(figure1,'PaperOrientation','Landscape');

if(exist('OutputFilename'))
    saveas(figure1,OutputFilename);
end