function createfigure(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9, cdata10, cdata11, cdata12)
%CREATEFIGURE(CDATA1,CDATA2,CDATA3,CDATA4,CDATA5,CDATA6,CDATA7,CDATA8,CDATA9,CDATA10,CDATA11,CDATA12)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata
%  CDATA7:  image cdata
%  CDATA8:  image cdata
%  CDATA9:  image cdata
%  CDATA10:  image cdata
%  CDATA11:  image cdata
%  CDATA12:  image cdata

%  Auto-generated by MATLAB on 04-Oct-2016 17:39:59

% Create figure
figure1 = figure;

% Create axes
axes('Visible','off','Parent',figure1);

% Create title
title('Volume Homotopic Lag Map','Interpreter','none');

% Create axes
axes1 = axes('Visible','off','Parent',figure1,...
    'Position',[0.0369094488188976 0.536909448818898 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 64]);
hold(axes1,'all');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create axes
axes2 = axes('Visible','off','Parent',figure1,...
    'Position',[0.197424540682415 0.536909448818898 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 64]);
hold(axes2,'all');

% Create image
image(cdata2,'Parent',axes2,'CDataMapping','scaled');

% Create axes
axes3 = axes('Visible','off','Parent',figure1,...
    'Position',[0.357939632545932 0.536909448818898 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 64]);
hold(axes3,'all');

% Create image
image(cdata3,'Parent',axes3,'CDataMapping','scaled');

% Create axes
axes4 = axes('Visible','off','Parent',figure1,...
    'Position',[0.518454724409449 0.536909448818898 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 64]);
hold(axes4,'all');

% Create image
image(cdata4,'Parent',axes4,'CDataMapping','scaled');

% Create axes
axes5 = axes('Visible','off','Parent',figure1,...
    'Position',[0.678969816272966 0.536909448818898 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0 64]);
hold(axes5,'all');

% Create image
image(cdata5,'Parent',axes5,'CDataMapping','scaled');

% Create axes
axes6 = axes('Visible','off','Parent',figure1,...
    'Position',[0.839484908136483 0.536909448818898 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0 64]);
hold(axes6,'all');

% Create image
image(cdata6,'Parent',axes6,'CDataMapping','scaled');

% Create axes
axes7 = axes('Visible','off','Parent',figure1,...
    'Position',[0.0369094488188976 0.0738188976377953 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[0 64]);
hold(axes7,'all');

% Create image
image(cdata7,'Parent',axes7,'CDataMapping','scaled');

% Create axes
axes8 = axes('Visible','off','Parent',figure1,...
    'Position',[0.197424540682415 0.0738188976377953 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[0 64]);
hold(axes8,'all');

% Create image
image(cdata8,'Parent',axes8,'CDataMapping','scaled');

% Create axes
axes9 = axes('Visible','off','Parent',figure1,...
    'Position',[0.357939632545932 0.0738188976377953 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[0 64]);
hold(axes9,'all');

% Create image
image(cdata9,'Parent',axes9,'CDataMapping','scaled');

% Create axes
axes10 = axes('Visible','off','Parent',figure1,...
    'Position',[0.518454724409449 0.0738188976377953 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes10,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes10,[0 64]);
hold(axes10,'all');

% Create image
image(cdata10,'Parent',axes10,'CDataMapping','scaled');

% Create axes
axes11 = axes('Visible','off','Parent',figure1,...
    'Position',[0.678969816272966 0.0738188976377953 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes11,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes11,[0 64]);
hold(axes11,'all');

% Create image
image(cdata11,'Parent',axes11,'CDataMapping','scaled');

% Create axes
axes12 = axes('Visible','off','Parent',figure1,...
    'Position',[0.839484908136483 0.0738188976377953 0.148211942257218 0.438484251968504],...
    'CLim',[-8 8]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes12,[0 48]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes12,[0 64]);
hold(axes12,'all');

% Create image
image(cdata12,'Parent',axes12,'CDataMapping','scaled');

% Create colorbar
colorbar('peer',axes12);

