#!/bin/bash

PID=$1


# Preapre .m file 

mfile=${PID}"BP.m"
if [ -e  $mfile ]
then
	rm $mfile
fi
touch $mfile

echo "addpath('/data/nil-bluearc/mintun/SuY/matlabcodes/');" >>$mfile #addpath
echo "ROIana('"$PID"');" >>$mfile
echo "MCBP('"$PID"');" >>$mfile

#-----------------------------------------------------------------------------------------------------------------------#
#--Execute matlab file -------------------------------------------------------------------------------------------------#
$MLBIN/matlab -nojvm -nodisplay < $mfile > /dev/null
rm $mfile

