#!/bin/bash
# Yi Su, 08/04/2011                                                            
loc=/data/nil-bluearc/mintun-DIAN/qmeta/AnaMaria/CBFcomp/asl_norm_f0/raw
norms=( AG1 AT1 CO1 DH1 DP1 JJ1 RM1  MS1 TJ1 )
hypos=( AG2 AT2 CO2 DH2 DP2 JJ2 RM2  MS2 TJ2 )
echo ${norms[*]}

opts=( norms.txt hypos.txt )
lr1=( Left- Right- )
lr2=( ctx-lh- ctx-rh- )
lr3=( wm-lh- wm-rh- )

nline=`wc -l /data/nil-bluearc/benzinger2/suy/ROIs | gawk '{print $1}'`
ns=9
for (( i=1; i<=$nline; i++ ))
do
	ROI=`gawk 'NR=='$i' {print $1}'  /data/nil-bluearc/benzinger2/suy/ROIs`
	flag=`gawk 'NR=='$i' {print $2}'  /data/nil-bluearc/benzinger2/suy/ROIs`
	if (( $flag == 1 ))
	then		
		for (( k=0; k<2; k++ ))
		do
			for (( l=0; l<2; l++ ))
			do
				region=${lr1[$l]}$ROI
				string="`printf '%-35s' $region`"
				for (( j=0; j<$ns; j++ ))
				do
					if (( $k == 0 )); then f0=${norms[$j]}; fi
					if (( $k == 1 )); then f0=${hypos[$j]}; fi
					v=`gawk '/'$region'/ {print $3}' $loc/${f0}"_avgz_norm_ROI3_f0"`
					string=${string}`printf ' %11.5f' $v`
				done
				echo $string >> ${opts[$k]}
			done
		done
		
	elif (( $flag == 0 ))
	then
		for (( k=0; k<2; k++ ))
		do
				region=$ROI
				string="`printf '%-35s' $region`"
				for (( j=0; j<$ns; j++ ))
				do
					if (( $k == 0 )); then f0=${norms[$j]}; fi
					if (( $k == 1 )); then f0=${hypos[$j]}; fi
					v=`gawk '/'$region'/ {print $3}' $loc/${f0}"_avgz_norm_ROI3_f0"`
					string=${string}`printf ' %11.5f' $v`
				done
				echo $string >> ${opts[$k]}
		done

	elif (( $flag == 2 ))
	then
		for (( k=0; k<2; k++ ))
		do
			for (( l=0; l<2; l++ ))
			do
				region=${lr2[$l]}$ROI
				string="`printf '%-35s' $region`"
				for (( j=0; j<$ns; j++ ))
				do
					if (( $k == 0 )); then f0=${norms[$j]}; fi
					if (( $k == 1 )); then f0=${hypos[$j]}; fi
					v=`gawk '/'$region'/ {print $3}' $loc/${f0}"_avgz_norm_ROI3_f0"`
					string=${string}`printf ' %11.5f' $v`
				done
				echo $string >> ${opts[$k]}
			done
		done

		for (( k=0; k<2; k++ ))
		do
			for (( l=0; l<2; l++ ))
			do
				region=${lr3[$l]}$ROI
				string="`printf '%-35s' $region`"
				for (( j=0; j<$ns; j++ ))
				do
					if (( $k == 0 )); then f0=${norms[$j]}; fi
					if (( $k == 1 )); then f0=${hypos[$j]}; fi
					v=`gawk '/'$region'/ {print $3}' $loc/${f0}"_avgz_norm_ROI3_f0"`
					string=${string}`printf ' %11.5f' $v`
				done
				echo $string >> ${opts[$k]}
			done
		done

	fi	
done
