#!/bin/bash
# Summarize calculated Abeta retention values.
# 03/16/2011 Yi Su

contents=( $(cat "$1") )
n=`wc -l "$1" | gawk '{print $1}'`

if [ -e BP.csv ] 
then 
	rm BP.csv
fi

printf "MAPID,PIB_SESSION_ID," >> BP.csv
for (( i=2; i<90; i++ ))
do
	value=`gawk 'NR=='$i' {print $1}'  10064/PIB424/PIB424pib1_ROIPIB.txt`
	printf "%s," $value >> BP.csv
done
value=`gawk 'NR=='$i' {print $1}'  10064/PIB424/PIB424pib1_ROIPIB.txt`
printf "%s\n" $value >> BP.csv
cp BP.csv BPRSF.csv
cp BP.csv SUVR.csv
cp BP.csv SUVRRSF.csv
cp BP.csv NVOX.csv 

for (( j=0; j<$n; j++ ))
do
	let "a = $j * 3"
	let "b = $a + 1"
	let "c = $a + 2"
	echo  -e "${contents[$a]}\t${contents[$b]}\t${contents[$c]}.v"
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> BP.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> SUVR.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> SUVRRSF.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> BPRSF.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> NVOX.csv
	for (( i=2; i<90; i++ ))
	do
		value=`gawk 'NR=='$i' {print $2}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
		printf "%s," $value >> NVOX.csv
		value=`gawk 'NR=='$i' {print $3}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
		printf "%s," $value >> BP.csv
		value=`gawk 'NR=='$i' {print $4}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
		printf "%s," $value >> BPRSF.csv
		value=`gawk 'NR=='$i' {print $5}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
		printf "%s," $value >> SUVR.csv
		value=`gawk 'NR=='$i' {print $6}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
		printf "%s," $value >> SUVRRSF.csv
	done
	value=`gawk 'NR=='$i' {print $2}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
	printf "%s\n" $value >> NVOX.csv
	value=`gawk 'NR=='$i' {print $3}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
	printf "%s\n" $value >> BP.csv
	value=`gawk 'NR=='$i' {print $4}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
	printf "%s\n" $value >> BPRSF.csv
	value=`gawk 'NR=='$i' {print $5}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
	printf "%s\n" $value >> SUVR.csv
	value=`gawk 'NR=='$i' {print $6}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_ROIPIB.txt"`
	printf "%s\n" $value >> SUVRRSF.csv	
done
