#!/bin/bash
# Summarize calculated Abeta retention values for manual drawn ROIs.
# 03/22/2011 Yi Su

contents=( $(cat "$1") )
n=`wc -l "$1" | gawk '{print $1}'`

if [ -e BPMAN.csv ] 
then 
	rm BPMAN.csv
fi

printf "MAPID,PIB_SESSION_ID," >> BPMAN.csv
for (( i=2; i<11; i++ ))
do
	value=`gawk 'NR=='$i' {print $1}'  10064/PIB424/PIB424pib1_MANPIB.txt`
	printf "%s," $value >> BPMAN.csv
done
value=`gawk 'NR=='$i' {print $1}'  10064/PIB424/PIB424pib1_MANPIB.txt`
printf "%s\n" $value >> BPMAN.csv
cp BPMAN.csv BPMANPVC2C.csv
cp BPMAN.csv SUVRMAN.csv
cp BPMAN.csv SUVRMANPVC2C.csv

for (( j=0; j<$n; j++ ))
do
	let "a = $j * 3"
	let "b = $a + 1"
	let "c = $a + 2"
	echo  -e "${contents[$a]}\t${contents[$b]}\t${contents[$c]}.v"
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> BPMAN.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> SUVRMAN.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> SUVRMANPVC2C.csv
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> BPMANPVC2C.csv

	for (( i=2; i<11; i++ ))
	do
		value=`gawk 'NR=='$i' {print $3}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
		printf "%s," $value >> BPMAN.csv
		value=`gawk 'NR=='$i' {print $4}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
		printf "%s," $value >> BPMANPVC2C.csv
		value=`gawk 'NR=='$i' {print $5}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
		printf "%s," $value >> SUVRMAN.csv
		value=`gawk 'NR=='$i' {print $6}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
		printf "%s," $value >> SUVRMANPVC2C.csv
	done
	value=`gawk 'NR=='$i' {print $3}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
	printf "%s\n" $value >> BPMAN.csv
	value=`gawk 'NR=='$i' {print $4}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
	printf "%s\n" $value >> BPMANPVC2C.csv
	value=`gawk 'NR=='$i' {print $5}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
	printf "%s\n" $value >> SUVRMAN.csv
	value=`gawk 'NR=='$i' {print $6}'  ${contents[$a]}/${contents[$b]}/${contents[$c]}"_MANPIB.txt"`
	printf "%s\n" $value >> SUVRMANPVC2C.csv	
done
