#!/bin/bash
#
# Script to generate time activity curves for arterial roi,
# halo roi, arterial+halo roi, for further analysis.
#
# Yi Su, 11/14/2013

datafn=$1
dataroot=${datafn%%.*}
TOFfn=$2
TOFname=`basename $TOFfn`
TOFdir=`dirname $TOFfn`
TOFroot=${TOFname%%.*}
mrfn=$3
mrname=`basename $mrfn`
mrdir=`dirname $mrfn`
mrroot=${mrname%%.*}

echo "TOF= "$TOFroot
echo "data = " $dataroot
echo "mrroot= " $mrroot
tardir=/data/cninds01/data2/atlas/
target=TRIO_Y_NDC
normfwhm=5.0

frames=`gawk '/matrix size \[4\]/ {print $NF}' ${dataroot}".4dfp.ifh"`
echo $frames
# sum pet images
sum_pet_4dfp ${dataroot} 1 $frames -h122.3 ${dataroot}_auto

# segment TOF-MRA
emmraseg $TOFfn
emmraabseg $TOFfn

# gaussian blur arterial mask
fwhm=8.0
f_half=$(echo "scale=6; 4.412712/$fwhm" | bc)
gauss_4dfp TOF_ART $f_half TOF_ART_gPET
gauss_4dfp TOF_AB $f_half TOF_AB_gPET

# Register TOF to T1
reg2img $mrroot $TOFroot

# Register T1 to atlas
mpr2atl_4dfp ${mrroot} -T${tardir}/${target}
msktgen_4dfp ${mrroot} -T${tardir}/${target}

# Register PET to T1
reg2img $mrroot ${dataroot}"_auto" -rm ${mrroot}_mskt.4dfp.img -rb 8 -mb 6

# PETFOV
tv=`imgmax_4dfp -m ${dataroot}"_auto" | gawk ' {print $2-1.0}'`
maskimg_4dfp -v1 -t${tv} ${dataroot}"_auto" ${dataroot}"_auto" temp$$
nsl=`gawk '/matrix size \[3\]/ {print $NF}' ${dataroot}"_auto.4dfp.ifh"`
zero_slice_4dfp temp$$ z 1 5  temp$$"_mskz"
k=$((nsl-4))
zero_slice_4dfp temp$$"_mskz" z $k $nsl  temp$$"_msk"
t4img_4dfp ${dataroot}_auto_to_${mrroot}_t4 temp$$"_msk" temp$$"_msk_on_MR" -O${mrroot} -n
tv=`imgmax_4dfp -m ${mrroot} | gawk ' {print $2-1.0}'`
maskimg_4dfp -R -v1 ${mrroot} temp$$"_msk_on_MR" PETFOV
rm temp*

# Find ART mask 
genericAIFFOVloc=/data/nil-bluearc/raichle/suy/BrainIF/NP872_EV
t4_inv ${mrroot}_to_${target}_t4 -u
t4img_4dfp ${target}_to_${mrroot}_t4 $genericAIFFOVloc/genericAIFROIatl AIFFOV -O$mrroot -n
maskimg_4dfp AIFFOV PETFOV AIFPETFOV

# get art roi tacs

t4img_4dfp ${TOFroot}_to_${mrroot}_t4 TOF_ART_gPET TOF_ART_gPET_on_MR -O${mrroot}
t4img_4dfp ${TOFroot}_to_${mrroot}_t4 TOF_AB_gPET TOF_AB_gPET_on_MR -O${mrroot}
t1=`findtroisize TOF_ART_gPET_on_MR AIFPETFOV 16000`
t2=`findtroisize TOF_ART_gPET_on_MR AIFPETFOV 8000`
echo $t1 $t2
maskimg_4dfp -t$t1 AIFPETFOV TOF_ART_gPET_on_MR artm1
maskimg_4dfp -t$t2 AIFPETFOV TOF_ART_gPET_on_MR artm2
imgopr_4dfp -sbartm1 artm1 artm2

a1PET=`qnt_4dfp TOF_ART_gPET_on_MR artm1 | gawk '/Mean/ {print $2}'`
a2PET=`qnt_4dfp TOF_ART_gPET_on_MR artm2 | gawk '/Mean/ {print $2}'`
a3PET=`qnt_4dfp TOF_ART_gPET_on_MR bartm1 | gawk '/Mean/ {print $2}'`

b1PET=`qnt_4dfp TOF_AB_gPET_on_MR artm1 | gawk '/Mean/ {print $2}'`
b2PET=`qnt_4dfp TOF_AB_gPET_on_MR artm2 | gawk '/Mean/ {print $2}'`
b3PET=`qnt_4dfp TOF_AB_gPET_on_MR bartm1 | gawk '/Mean/ {print $2}'`

if [ -e ${dataroot}_abPET.txt ]
then
	rm  ${dataroot}_abPET.txt
fi
touch ${dataroot}_abPET.txt
printf "%16s%16s\n" Region RC >> ${dataroot}_abPET.txt
printf "%16s%16f\n" ART1 $a1PET >> ${dataroot}_abPET.txt
printf "%16s%16f\n" ART2 $a2PET >> ${dataroot}_abPET.txt
printf "%16s%16f\n" BART1 $a3PET >> ${dataroot}_abPET.txt

if [ -e ${dataroot}_bPET.txt ]
then
	rm  ${dataroot}_bPET.txt
fi
touch ${dataroot}_bPET.txt
printf "%16s%16s\n" Region RC >> ${dataroot}_bPET.txt
printf "%16s%16f\n" ART1 $b1PET >> ${dataroot}_bPET.txt
printf "%16s%16f\n" ART2 $b2PET >> ${dataroot}_bPET.txt
printf "%16s%16f\n" BART1 $b3PET >> ${dataroot}_bPET.txt

if [ -e ${dataroot}_art1.tac ]
then
	rm ${dataroot}_art1.tac
fi
touch ${dataroot}_art1.tac
if [ -e ${dataroot}_art2.tac ]
then
	rm ${dataroot}_art2.tac
fi
touch ${dataroot}_art2.tac
if [ -e ${dataroot}_bart1.tac ]
then
	rm ${dataroot}_bart1.tac
fi
touch ${dataroot}_bart1.tac



t4file=${dataroot}"_auto_to_"${mrroot}"_t4"
f_half=$(echo "scale=6; 4.412712/$normfwhm" | bc)


for (( f=1; f<=$frames; f++ ))
do
	echo $f
	chop_4dfp $datafn $f $f -o${dataroot}"_"$f
	t4img_4dfp $t4file ${dataroot}"_"$f PET_on_MR -O$mrroot
	gauss_4dfp PET_on_MR $f_half PET_on_MR_8mm
	qnt_4dfp PET_on_MR_8mm artm1 | gawk '/Mean/ {print $2}' >> ${dataroot}_art1.tac
	qnt_4dfp PET_on_MR_8mm artm2 | gawk '/Mean/ {print $2}' >> ${dataroot}_art2.tac
	qnt_4dfp PET_on_MR_8mm bartm1 | gawk '/Mean/ {print $2}' >> ${dataroot}_bart1.tac
#	roieval PET_on_MR_8mm RSFMask PETFOV $ROIlist $NROI ${dataroot} $f
#	qnt_4dfp PET_on_MR_8mm WBMask | gawk '/Mean/ {print $2}' >> ${dataroot}_WB.tac
	rm ${dataroot}"_"${f}.*
done

