#!/bin/bash
###############################################################################
# Program to correct e7 dicom outputs				              #
###############################################################################
# Yi Su, 2015/3/13

DOSE=`dcmdump +P 0054,0016 *.1.dcm 2>/dev/null  | grep TotalDose | sed 's/\[//' | sed 's/\]//' | gawk '{print $3}'`
WEIGHT=`dcmdump +P 0010,1030 *.1.dcm 2>/dev/null | sed 's/\[//' | sed 's/\]//' | gawk '{print $3}'`
echo $DOSE, $WEIGHT,
