#!/bin/bash
################################################################################
# Program that combines Jon's manual drawn ROIs into a single file for further #
# processing with PUP processing scripts				       #
################################################################################
# Yi Su, 01/31/2014

idstr='$Id: mancomb,v 1.0 Fri Jan 31 09:40:11 CST 2014 suy $'

echo $idstr

program=`basename $0`

if [ $# -lt 2 ]
then
	echo "Usage: $program mrid roilist"
	exit -1
fi

mrid=$1
roilist=$2

NROI=`wc -l $roilist | gawk '{print $1}'`

roi=brainstem
roifn=${mrid}_${roi}
analyzeto4dfp $roifn

# generate support image
maskimg_4dfp $roifn $roifn ones -t-1 -v1

inc=1
for (( i=2; i<=NROI; i++ ))
do
	roi=`gawk 'NR=='$i' {print $1}' $roilist`
	roifn=${mrid}_${roi}
	analyzeto4dfp $roifn
	scale_4dfp ones $inc -a$inc
	imgopr_4dfp -a${roifn}${inc} ${roifn} ones_$inc
	maskimg_4dfp ${roifn}${inc} ${roifn} ${roifn}${inc}m
	rm ${roifn}.4dfp.*
	rm ${roifn}${inc}.4dfp.*
	(( inc+=2 ))
done
rm ones*
imgopr_4dfp -xmanroi *.4dfp.img
bo=`gawk '/byte order/{print $5}' manroi.4dfp.ifh`
cp $RELEASE/222.4dfp.ifh manroi.4dfp.ifh
sed -i 's/bigendian/'$bo'/g' manroi.4dfp.ifh
ifh2hdr manroi

(( nb=inc+1 ))
ub=$(echo "scale=6; $nb-0.5" |bc)
img_hist_4dfp manroi -b$nb -r-.5to$ub | tail -$nb >vc.txt

nv=`gawk 'NR==2 {print $2}' vc.txt`
printf "%-35s %10d %10d\n" brainstem 1 $nv > manroi.txt

l=2
for (( i=2; i<=NROI; i++ ))
do
	roi=`gawk 'NR=='$i' {print $1}' $roilist`
	lroi="left-"$roi
	(( l++ )) 
	nv=`gawk 'NR=='$l' {print $2}' vc.txt`
	(( l-- ))
	printf "%-35s %10d %10d\n" $lroi $l $nv >> manroi.txt
	(( l++ ))	
	rroi="right-"$roi
	(( l++ )) 
	nv=`gawk 'NR=='$l' {print $2}' vc.txt`
	(( l-- ))
	printf "%-35s %10d %10d\n" $rroi $l $nv >> manroi.txt
	(( l++ ))
done



