#!/bin/bash
################################################################################
#									       #
# Script to prepare for PVC analysis and generating whole brain mask	       #
# USAGE:								       #
#	pettacpre paramsfn                                                     #
#									       #
################################################################################
# Yi Su, 12/19/2016
VERSION=1.0

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Mon Dec 19 13:19:31 CST 2016 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1

# Read PARAMS file
source $paramsfn

###############################################################################
# RSF preprocessing if requested
if (( rsfflag == 1 ))
then
	echo 1
	calrsfmat $roiimg $roilist RSFMat.dat $fwhm || die "$program ERROR: calrsfmat $roiimg $roilist RSFMat.dat $fwhm failed"
fi

###############################################################################
# PVC2C preprocessing if requested
if (( pvc2cflag == 1 ))
then
	imgblur_4dfp BrainMask $fwhm || die "$program ERROR: imgblur_4dfp BrainMask $fwhm failed"
	bx=`echo $fwhm | awk '{print 10*$1}'`
	bstr="_b"$bx
	NROI=`wc -l $roilist | gawk '{print $1}'`
	roieval3 BrainMask${bstr} $roiimg PETFOV $roilist $NROI pvc2c 0 || die "$program ERROR: roieval3 BrainMask${bstr} $roiimg PETFOV $roilist $NROI pvc2c 0 failed"
	mv pvc2c_ROI2_f0 pvc2c.txt
fi
echo 2
###############################################################################
# Find whole brain mask
t=`gawk '/Right-UnsegmentedWhiteMatter/ {print $2}' ${roilist}`
t=$(echo "scale=3; $t+0.5" |bc)
zero_gt_4dfp $t $roiimg
maskimg_4dfp  PETFOV ${roiimg}z WBMask
rm ${roiimg}z.*
echo 3
