#!/bin/bash
###################--------------------------------------------------------------
# The purpose of this program is to create early, middle, and late PIB PET
# images from dynamic ECAT PIB PET scans. 

#   PIB 54 frames:
#   PET Images:        a1 a2 a3 b1 b2 b3 c1 c2 c3
#   PET Minutes:        5  5  5  5  5  5 10 10 10
#   set startframe = (  2 36 41 46 47 48 49 51 53 )
#   set lastframe =  ( 35 40 45 46 47 48 50 52 54 )

#   DLBPIB and Test-Retest 32 and 34 frames:
#   PET Images:        a1 a2 a3 b1 b2 b3 c1 c2 c3
#   PET Minutes:        5  5  4  6  5  5 10 10 10
#   set startframe = (  2 13 18 22 24 25 26 28 30 32 34 )
#   set lastframe =  ( 12 17 21 23 24 25 27 29 31 32 34 )

#   PIB 26 frames:
#   PET Images:        a1 a2 a3 b1 b2 b3 c1 c2 c3
#   PET Minutes:        4  5  5  5  5  5 10 10 10
#   set startframe = (  2 17 18 19 20 21 22 24 26 )
#   set lastframe =  ( 16 17 18 19 20 21 23 25 27 )
###################--------------------------------------------------------------
# Inputs to the program
#
# $1: ECAT PET file name (*.v)
#
###################--------------------------------------------------------------
# Yi Su, 10/08/2010                                                            

if (( $# < 1 ))
then
	echo "Usage: `basename $0` ecatfile.v"
	exit 1
fi

ecatfstr=$1
#any argument after the first are ignored
outname=`basename $ecatfstr`
outroot=${outname%.*}

frames=`ecat_header $ecatfstr | gawk '/Number of Frames/ {print $5}'`

PIBFLAG=0
if (( $frames == 54 ))
then
	PIBFLAG=1
elif (( $frames == 32 ))
then
	PIBFLAG=2
elif (( $frames == 33 ))
then
	PIBFLAG=2
elif (( $frames == 34 ))
then
	PIBFLAG=2
elif (( $frames == 27 ))
then
	PIBFLAG=3
fi

if (( $PIBFLAG == 0 ))
then
	echo "ERROR PIBFLAG = 0 Must Exit"
	exit 1
fi

if (( $PIBFLAG == 1 ))
then
	echo "54 Frame ECAT Sequence"
	groups=( a b c )
	startframe=( 2 36 41 46 47 48 49 51 53 )
	lastframe=( 35 40 45 46 47 48 50 52 54 )
fi

if (( $PIBFLAG == 2 ))
then
	echo "32 to 34 Frame ECAT Sequence"
	groups=( a b c )
	startframe=( 2 13 18 22 24 25 26 28 30 )
	lastframe=( 12 17 21 23 24 25 27 29 31 )
fi


if (( $PIBFLAG == 3 ))
then
	echo "27 Frame ECAT Sequence"
	groups=( a b c )
	startframe=( 2 17 18 19 20 21 22 24 26 )
	lastframe=( 16 17 18 19 20 21 23 25 27 )
fi

for (( g=0; g<3; g++ ))
do
	for (( i=0; i<3; i++ ))
	do
		echo ${outroot}"_"${groups[$g]}$((i+1))
		echo ~suy/bin/sumecatto4dfp $ecatfstr ${outroot}"_"${groups[$g]}$((i+1)) ${startframe[$((i+g*3))]}  ${lastframe[$((i+g*3))]} 
		~suy/bin/sumecatto4dfp $ecatfstr ${outroot}"_"${groups[$g]}$((i+1)) ${startframe[$((i+g*3))]}  ${lastframe[$((i+g*3))]} 
	done
done
