#!/bin/bash
###################--------------------------------------------------------------
# The purpose of this program is to create .info file based on the dynamic 4dfp file
# in the order of: start time, frame time, duration, decay correction factor, frame number
###################--------------------------------------------------------------
# Inputs to the program
#
# $1: 4dfp PET file name (*.4dfp.img) assuming the frame duration and decay correction info is in the .rec file
#
###################--------------------------------------------------------------
# Yi Su, 11/03/2010                                                            

petfstr=$1
petdir=`dirname $petfstr`
petname=`basename $petfstr`
petroot=${petname%.*}
petroot=${petroot%.*}

frames=`gawk '/matrix size \[4\]/ {print $5}' $petdir"/"$petroot".4dfp.ifh"`
if [ -e  $petroot".info" ]
then
	rm $petroot".info"
fi
touch $petroot".info"

st=0
for (( f=1; f<=$frames; f++ ))
do
	fd=`gawk '/Frame_'$f' / {print $2/1000}' $petdir"/"$petroot".4dfp.img.rec"`
	dc=`gawk '/Frame_'$f' / {print $7}' $petdir"/"$petroot".4dfp.img.rec"`
	t=$(echo "scale=8; $st+$fd/2" | bc)
	printf '%f\t%f\t%f\t%f\t%d\n' $st $t $fd $dc $f >> $petroot".info"
	st=$(echo "scale=8; $st+$fd" | bc)
done
