#!/bin/bash
################################################################################
# This program performs ROI analysis for PIB images using manually defined     #
# ROIs and t4 files created by PIBMPRREG which registers PIB images to the MR  #
# images. Manual ROIs are defined in atlas space but transformed into the MR   #
# space. Time-Activity-Curves are generated with and without PVC using the two #
# component model.                                                             #
################################################################################
# Yi Su, 03/21/2011                                                            

ecatfstr=$1 # ECAT PET image file (.v)
fsfstr=$2   # Freesurfer ROI definition file (usually wmparc.mgz)

			
petname=`basename $ecatfstr`
petdir=`dirname $ecatfstr`
petroot=${petname%.*}
fsfname=`basename $fsfstr`
fsfdir=`dirname $fsfstr`
fsfroot=${fsfname%.*}
fsfroot=${fsfroot}"001"

mrroot=T1001
#############################
# Determine frame separation scheme for the PIB data

frames=`ecat_header $ecatfstr | gawk '/Number of Frames/ {print $5}'`

PIBFLAG=0
if (( $frames == 54 ))
then
	PIBFLAG=1
elif (( $frames == 32 ))
then
	PIBFLAG=2
elif (( $frames == 33 ))
then
	PIBFLAG=2
elif (( $frames == 34 ))
then
	PIBFLAG=2
elif (( $frames == 27 ))
then
	PIBFLAG=3
fi

if (( $PIBFLAG == 0 ))
then
	echo "ERROR PIBFLAG = 0 Must Exit"
	exit 1
fi

if (( $PIBFLAG == 1 ))
then
	echo "54 Frame ECAT Sequence"
	groups=( a b c )
	startframe=( 2 36 41 46 47 48 49 51 53 )
	lastframe=( 35 40 45 46 47 48 50 52 54 )
fi

if (( $PIBFLAG == 2 ))
then
	echo "32 to 34 Frame ECAT Sequence"
	groups=( a b c )
	startframe=( 2 13 18 22 24 25 26 28 30 )
	lastframe=( 12 17 21 23 24 25 27 29 31 )
fi


if (( $PIBFLAG == 3 ))
then
	echo "27 Frame ECAT Sequence"
	groups=( a b c )
	startframe=( 2 17 18 19 20 21 22 24 26 )
	lastframe=( 16 17 18 19 20 21 23 25 27 )
fi

###########################
# Manual roi analysis
PVC2CMAN $fsfroot PETFOV 6.0

if [ -e brainstemROI.4dfp.img ]
then
	maskimg_4dfp brainstemROI PETFOV brainstemROIPET
	NVOX=`qnt_4dfp brainstemROIPET brainstemROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_brainstemROI.tac"
fi
if [ -e caudateROI.4dfp.img ]
then
	maskimg_4dfp caudateROI PETFOV caudateROIPET
	NVOX=`qnt_4dfp caudateROIPET caudateROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_caudateROI.tac"
fi
if [ -e cerebellumROI.4dfp.img ]
then
	maskimg_4dfp cerebellumROI PETFOV cerebellumROIPET
	NVOX=`qnt_4dfp cerebellumROIPET cerebellumROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_cerebellumROI.tac"
fi
if [ -e gyrusrectusROI.4dfp.img ]
then
	maskimg_4dfp gyrusrectusROI PETFOV gyrusrectusROIPET
	NVOX=`qnt_4dfp gyrusrectusROIPET gyrusrectusROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_gyrusrectusROI.tac"
fi
if [ -e lattempROI.4dfp.img ]
then
	maskimg_4dfp lattempROI PETFOV lattempROIPET
	NVOX=`qnt_4dfp lattempROIPET lattempROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_lattempROI.tac"
fi
if [ -e occipitalROI.4dfp.img ]
then
	maskimg_4dfp occipitalROI PETFOV occipitalROIPET
	NVOX=`qnt_4dfp occipitalROIPET occipitalROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_occipitalROI.tac"
fi
if [ -e parietalROI.4dfp.img ]
then
	maskimg_4dfp parietalROI PETFOV parietalROIPET
	NVOX=`qnt_4dfp parietalROIPET parietalROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_parietalROI.tac"
fi
if [ -e precuneusROI.4dfp.img ]
then
	maskimg_4dfp precuneusROI PETFOV precuneusROIPET
	NVOX=`qnt_4dfp precuneusROIPET precuneusROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_precuneusROI.tac"
fi
if [ -e prefrontalROI.4dfp.img ]
then
	maskimg_4dfp prefrontalROI PETFOV prefrontalROIPET
	NVOX=`qnt_4dfp prefrontalROIPET prefrontalROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_prefrontalROI.tac"
fi
if [ -e rostralROI.4dfp.img ]
then
	maskimg_4dfp rostralROI PETFOV rostralROIPET
	NVOX=`qnt_4dfp rostralROIPET rostralROIPET | gawk '/Voxels/ {print $2}'`
	printf "%9s %15s %15s %15s %15s %15s %10d\n" "Frame_#" "Start_Time_(m)" "Duration_(m)"  "Mean" "Mean_(PVC)" "NVoxels=" $NVOX > ${petroot}"_rostralROI.tac"
fi


for (( f=2; f<=frames; f++ ))
do
	ecat_header $ecatfstr $f >& /dev/null
	if [ $? -eq 0 ]
	then
		~suy/bin/ecatto4dfp $ecatfstr ${petroot}"_"$f 1 $f $f
		if (( $f < ${startframe[1]} )) 
		then
			t4file=${petroot}"_a1_to_MR_t4"
		elif (( $f < ${startframe[2]} )) 
		then
			t4file=${petroot}"_a2_to_MR_t4"
		elif (( $f < ${startframe[3]} )) 
		then
			t4file=${petroot}"_a3_to_MR_t4"
		elif (( $f < ${startframe[4]} )) 
		then
			t4file=${petroot}"_b1_to_MR_t4"
		elif (( $f < ${startframe[5]} )) 
		then
			t4file=${petroot}"_b2_to_MR_t4"
		elif (( $f < ${startframe[6]} )) 
		then
			t4file=${petroot}"_b3_to_MR_t4"
		elif (( $f < ${startframe[7]} )) 
		then
			t4file=${petroot}"_c1_to_MR_t4"
		elif (( $f < ${startframe[8]} )) 
		then
			t4file=${petroot}"_c2_to_MR_t4"
		else
			t4file=${petroot}"_c3_to_MR_t4"
		fi
		t4img_4dfp $t4file ${petroot}"_"$f  ${petroot}"_"$f"_on_MR" -O${mrroot} # Transform the frame to MR space
		if [ -e brainstemROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" brainstemROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/brainstemROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_brainstemROI.tac"
		fi

		if [ -e caudateROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" caudateROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/caudateROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_caudateROI.tac"
		fi
		
		if [ -e cerebellumROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" cerebellumROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/cerebellumROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_cerebellumROI.tac"
		fi
		
		if [ -e gyrusrectusROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" gyrusrectusROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/gyrusrectusROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_gyrusrectusROI.tac"
		fi
		
		if [ -e lattempROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" lattempROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/lattempROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_lattempROI.tac"
		fi
		
		if [ -e occipitalROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" occipitalROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/occipitalROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_occipitalROI.tac"
		fi
		
		if [ -e precuneusROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" precuneusROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/precuneusROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_precuneusROI.tac"
		fi
		
		if [ -e prefrontalROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" prefrontalROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/prefrontalROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_prefrontalROI.tac"
		fi
		
		if [ -e parietalROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" parietalROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/parietalROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_parietalROI.tac"
		fi
		
		if [ -e rostralROIPET.4dfp.img ]
		then
			mean=`qnt_4dfp ${petroot}"_"$f"_on_MR" rostralROIPET | gawk '/Mean/ {print $2}'`
			ts=`gawk '{print $1}' ${petroot}"_"$f".info"`
			td=`gawk '{print $3}' ${petroot}"_"$f".info"`
			pvcf=`gawk '/rostralROI/ {print $2}' PVC2CMAN.txt`
			meanpvc=$(echo "scale=8; $mean / $pvcf" | bc)
			printf "%9d %15f %15f %15f %15f\n" $f $ts $td $mean $meanpvc >> ${petroot}"_rostralROI.tac"
		fi
		rm ${petroot}"_"${f}.*
		rm ${petroot}"_"${f}_on_MR.*
	fi
done
