#!/bin/bash
# Summarize calculated Abeta retention values for manual drawn ROIs.
# 03/22/2011 Yi Su

contents=( $(cat "$1") )
n=`wc -l "$1" | gawk '{print $1}'`

if [ -e MANPVC.csv ] 
then 
	rm MANPVC.csv
fi

printf "MAPID,PIB_SESSION_ID," >> MANPVC.csv
for (( i=1; i<10; i++ ))
do
	value=`gawk 'NR=='$i' {print $1}'  10064/PIB424/PVC2CMAN.txt`
	printf "%s," $value >> MANPVC.csv
done
value=`gawk 'NR=='$i' {print $1}'  10064/PIB424/PVC2CMAN.txt`
printf "%s\n" $value >> MANPVC.csv

for (( j=0; j<$n; j++ ))
do
	let "a = $j * 3"
	let "b = $a + 1"
	let "c = $a + 2"
	echo  -e "${contents[$a]}\t${contents[$b]}\t${contents[$c]}.v"
	printf "%s,%s," ${contents[$a]} ${contents[$b]} >> MANPVC.csv

	for (( i=1; i<10; i++ ))
	do
		value=`gawk 'NR=='$i' {print $2}'  ${contents[$a]}/${contents[$b]}/PVC2CMAN.txt`
		printf "%s," $value >> MANPVC.csv
	done
	value=`gawk 'NR=='$i' {print $2}'  ${contents[$a]}/${contents[$b]}/PVC2CMAN.txt`
	printf "%s\n" $value >> MANPVC.csv
done
