#!/bin/bash

TOFfn=$1
t4fn=$2
ArtInfo=$3
PET=$4
fdgflag=$5

# Calculate thresholds for generating arterial ROI and background ROI
p=`imgmax_4dfp ./AIF/$TOFfn"_Art_g"`
ta=$(echo "scale=6; $p/2." | bc)
tb=$(echo "scale=6; $ta/2." | bc)
#tb=0.02

echo $ta $tb


# Prepare .m file for extracting AIF./AIF/lArt"_"$PET
cd AIF
mfile=$PET"AIF.m"
if [ -e  $mfile ]
then
	rm $mfile
fi
touch $mfile
if [ "$fdgflag" -eq 1 ]
then
	dpetfn=${PET}"_on_"${PET}"_sumall"
else
	dpetfn=$PET
fi

echo "addpath('/data/nil-bluearc/mintun/SuY/matlabcodes/');" >>$mfile #addpath
echo "extractAIFt('../"$dpetfn"','lArt_"$PET"z','rArt_"$PET"z','"$TOFfn"_Art_g_"$PET"','"$PET"',"$ta","$tb");" >>$mfile

#-----------------------------------------------------------------------------------------------------------------------#
#--Execute matlab file -------------------------------------------------------------------------------------------------#
$MLBIN/matlab -nojvm -nodisplay < $mfile
#/opt/matlab8/bin/matlab -nojvm -nodisplay < $mfile
rm $mfile
cd ..
