#!/bin/bash

imgfn=$1


# Prepare .m file 

mfile=${imgfn}"wdn.m"
if [ -e  $mfile ]
then
	rm $mfile
fi
touch $mfile

echo "addpath('/data/nil-bluearc/mintun/SuY/matlabcodes/');" >>$mfile #addpath
echo "addpath('/data/nil-bluearc/mintun/SuY/matlabcodes/WSBP');" >>$mfile #addpath
echo "addpath('/data/nil-bluearc/mintun/SuY/matlabcodes/wdn');" >>$mfile #addpath
echo "wdn4dfp('"$imgfn"');" >>$mfile

#-----------------------------------------------------------------------------------------------------------------------#
#--Execute matlab file -------------------------------------------------------------------------------------------------#
$MLBIN/matlab -nojvm -nodisplay < $mfile #> /dev/null
rm $mfile
