#!/bin/bash
################################################################################
# Preprocessing FREESURFER output files for PET ROI analysis                   #
#                                   				               #
# USAGE:								       #
#	fspreproc1 paramsfn                                                    #
#                                                                              #
# This script reads a params file that includes:                               #
#	fsdir: location of FREESURFER mgz out files			       #
#	wmparc:	FREESURFER segmentation file (wmparc.mgz)		       #
#	t1: FREESURFER MR file (t1.mgz or orig.mgz)			       #
#									       #
#									       #
# The output of this program are converted FREESURFER files in 4dfp format     #
################################################################################
# Yi Su, 01/02/2014

idstr='$Id: fspreproc1,v 1.0 2014/01/02 18:07:48 suy Exp $'

echo $idstr

program=`basename $0`

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

paramsfn=$1
###############################################################################
# Read PARAMS file
source $paramsfn

# Further development will improve this program which checks the validity of
# the inputs specified in the params file

###############################################################################
cp $fsdir/$t1 .
cp $fsdir/$wmparc .

mgzto4dfp $t1
mgzto4dfp $wmparc

mrroot=${t1%.*}
mrroot=${mrroot}001
wmparcroot=${wmparc%.*}
wmparcroot=${wmparcroot}001
