#!/bin/bash
################################################################################
# Combining DICOM PET data encoded as multiple scans as a single multi-frame   #
# PET data in NIFTI format for PUP processing.                                 #
#                                                                              #
# USAGE:								       #
#	genniftipet inputlist outroot                                          #
#                                                                              #
# This script reads a text file that includes a list of folders each containing#
# DICOM files from a single frame in the order that was acquired.              #
#                                                                              #
# The output of this program would be a nifti PET pair (.nii and .csv) that    #
# contains the imaging data frame timing info.                                 #
################################################################################
# Yi Su, 05/09/2017

VERSION=1.0

if [ "$1" == "--version" ]; then
    echo $VERSION
    exit 0
fi

die(){
    echo >&2 "$@"
    exit -1
}

program=`basename $0`
idstr='$Id: '$program',v '$VERSION' Tue May  9 16:38:57 CDT 2017 suy $'
echo $idstr

if [ $# -lt 1 ]
then
	echo "Usage: $program paramsfn"
	exit -1
fi

infn=$1
outroot=$2

echo "Frame #,Duration of time frame (min),Total elapsed time (min)," > ${outroot}.csv

nf=`wc -l ${infn} | gawk '{print $1}'`
st=0
te=0
echo $nf
for (( f=1; f<=nf; f++ ))
do
	floc=`sed "${f}q;d" ${infn}`
	echo ${floc}
	dcm_pet -n -a -b ${outroot}_f${f} ${floc}/*.dcm
	echo ${outroot}_f${f} >> ${outroot}.lst
	fd=`gawk '/Frame_1 / {print $2/1000}' ${outroot}_f${f}".4dfp.img.rec"`
	fdm=$(echo "scale=6; $fd/60" | bc)
	te=$(echo "scale=6; $te+$fdm" | bc)
	echo ${f},${fdm},$te
	echo ${f},${fdm},$te >> ${outroot}.csv
done 

paste_4dfp -a ${outroot}.lst ${outroot}
nifti_4dfp -n ${outroot} ${outroot}

#clean up
rm *4dfp.*
rm ${outroot}.lst

