#!/bin/bash
################################################################################
# This program performs ROI analysis for PIB images based on freesurfer created#
# ROIs and t4 files created by PIBMPRREG which registers PIB images to the MR  #
# images. ROI analysis is performed with and without RSF based partial volume  #
# correction.                                                                  #
#                                                                              #
################################################################################
# Yi Su, 08/31/2011

idstr='$Id: PIBROIFS,v 1.2 2012/08/21 21:11:00 suy Exp $'
echo $idstr

petfstr=$1 # PET image file (.v or .4dfp.img)
fsfstr=$2   # Freesurfer ROI definition file (usually wmparc.mgz)
mrfstr=$3   # Anatomical MR file (usually T1.mgz)
fslut=$4
fwhm=$5

mgzto4dfp $fsfstr	# Converting to 4dfp file
			# The anatomical file (T1.mgz) has already been converted
			
petname=`basename $petfstr`
petdir=`dirname $petfstr`
petroot=${petname%%.*}
mrname=`basename $mrfstr`
mrdir=`dirname $mrfstr`
mrroot=${mrname%.*}
mrroot=${mrroot}"001"
fsfname=`basename $fsfstr`
fsfdir=`dirname $fsfstr`
fsfroot=${fsfname%.*}
fsfroot=${fsfroot}"001"
                                                     
#############################
# Determine frame separation scheme for the PIB data

source ${petroot}.tb

###########################
# Generating PET field of view converage file PETFOV.4dfp.img

tv=`imgmax_4dfp -m ${petroot}"_c" | gawk ' {print $2-1.0}'`
maskimg_4dfp -v1 -t${tv} ${petroot}"_c" ${petroot}"_c" temp$$
nsl=`gawk '/matrix size \[3\]/ {print $NF}' ${petroot}"_c.4dfp.ifh"`
zero_slice_4dfp temp$$ z 1 5  temp$$"_mskz"
tv=`imgmax_4dfp -m ${mrroot} | gawk ' {print $2-1.0}'`
k=$((nsl-4))
zero_slice_4dfp temp$$"_mskz" z $k $nsl  temp$$"_msk"
maskimg_4dfp -R -v1 -t${tv} ${mrroot} ${mrroot} PETFOV
groups=( a b c )
for (( g=0; g<3; g++ ))
do
	for (( i=1; i<4; i++ ))
	do
		t4file=${petroot}"_"${groups[$g]}$i"_to_MR_t4"
		t4img_4dfp $t4file temp$$"_msk" temp$$"_"${groups[$g]}$i -O${mrroot} -n
		maskimg_4dfp -R -v1 PETFOV PETFOV temp$$_1
		imgopr_4dfp -pPETFOV temp$$_1 temp$$"_"${groups[$g]}$i
	done
done
rm temp$$*.4dfp.*

###########################
# Processing freesurfer rois, whole head roi, and prepare for roi analysis

frames=`gawk '/matrix size \[4\]/ {print $5}' $petdir"/"$petroot".4dfp.ifh"`
maskimg_4dfp -v1 -t15 ${mrroot}"_g9"  ${mrroot}"_g9" Head_Mask
PreprocessRSFtest2 $fsfroot Head_Mask  RSFMask ROIlist.txt $fslut
calrsfmat RSFMask ROIlist.txt RSFMat.dat $fwhm
frames=${lastframe[8]}
for (( f=1; f<=frames; f++ ))
do
	if [ $? -eq 0 ]
	then
		chop_4dfp $petfstr $f $f -o${petroot}"_"$f
		if (( $f < ${startframe[1]} )) 
		then
			t4file=${petroot}"_a1_to_MR_t4"
		elif (( $f < ${startframe[2]} )) 
		then
			t4file=${petroot}"_a2_to_MR_t4"
		elif (( $f < ${startframe[3]} )) 
		then
			t4file=${petroot}"_a3_to_MR_t4"
		elif (( $f < ${startframe[4]} )) 
		then
			t4file=${petroot}"_b1_to_MR_t4"
		elif (( $f < ${startframe[5]} )) 
		then
			t4file=${petroot}"_b2_to_MR_t4"
		elif (( $f < ${startframe[6]} )) 
		then
			t4file=${petroot}"_b3_to_MR_t4"
		elif (( $f < ${startframe[7]} )) 
		then
			t4file=${petroot}"_c1_to_MR_t4"
		elif (( $f < ${startframe[8]} )) 
		then
			t4file=${petroot}"_c2_to_MR_t4"
		else
			t4file=${petroot}"_c3_to_MR_t4"
		fi
		t4img_4dfp $t4file ${petroot}"_"$f  ${petroot}"_"$f"_on_MR" -O${mrroot} # Transform the frame to MR space
		NROI=`wc -l ROIlist.txt | gawk '{print $1}'`
		rsfroieval2 ${petroot}"_"$f"_on_MR" RSFMask RSFMat.dat PETFOV ROIlist.txt $NROI 10 ${petroot} $f
		rm ${petroot}"_"${f}.*
		rm ${petroot}"_"${f}_on_MR.*
	fi
done

exit $?
