#!/bin/csh

if($#argv < 4) then
	echo "P2_batch <compute 2 account> <ProjectID with Processing Folder> <Subject List> <Commandline flags>
	echo "Project ID with processing folder means MRI/InProcess or MRI/Participants. It is where P2 will need to run from relative to the Projects Folder."
	echo "Subject List is a double quote wrapped list"
	echo "The command line directives are the things you want P2 to do, such as -reg -fMRI. It is double quote wrapped"
	exit 1
endif

set ComputeAccount = $1
set Project = $2
set SubjectList = ($3)
set Directives = ($4)

#pushd ${PROJECTS_HOME}/${PROJECTS_DIR}/$Project
#@ i = 2
#while($i <= $#argv)
#
#	set Directives = ($Directives $argv[$i])
#	@ i++
#end

if(! -e ~/P2_batch_jobs) then
	mkdir ~/P2_batch_jobs
endif

foreach subject($SubjectList)

	cp ${PP_SCRIPTS}/P2_template.sbatch ~/P2_batch_jobs/P2_batch_${subject}.sbatch 
	echo "#SBATCH -A ${ComputeAccount}" >> ~/P2_batch_jobs/P2_batch_${subject}.sbatch
	echo "#SBATCH --job-name=P2_${subject}" >> ~/P2_batch_jobs/P2_batch_${subject}.sbatch
	echo "pushd ${PROJECTS_HOME}/${PROJECTS_DIR}/$Project" >> ~/P2_batch_jobs/P2_batch_${subject}.sbatch
	echo "P2 $subject $Directives" >> ~/P2_batch_jobs/P2_batch_${subject}.sbatch

	sbatch ~/P2_batch_jobs/P2_batch_${subject}.sbatch &
end

echo "Finished submitting jobs"
exit 0
